title: Add title
body:
  - type: checkboxes
    attributes:
      label: Please select one or more topics you'd like to provide feedback on.
      options:
        - label: GREI Event (Webinar, Workshop, Community Call, etc)
          required: false
        - label: GREI Year 3 Objective, Task, or Deliverable
          required: false
        - label: GREI Resources (Comparison Chart, Selection Flowchart, etc)
          required: false
        - label: Other (please specify)
          required: false
          
  - type: input
    id: other_specify
    attributes:
      label: If applicable, what other topic would you like to provide feedback on?
      description: 
    validations:
      required: false
  
  - type: checkboxes
    attributes:
      label: If applicable, select the GREI Year 3 Objective, Task, or Deliverable.
      options:
        - label: Community Engagement (All units)
          required: false
        - label: Desirable  Repository Characteristics
          required: false
        - label: Consistent Metadata
          required: false
        - label: Search & Browse
          required: false
        - label: Analytics & Reporting
          required: false
        - label: Use Cases
          required: false
        - label: Connecting Digital Objects
          required: false
        - label: QA/QC
          required: false
        - label: Training & Community Engagement
          required: false


  - type: textarea
    id: question_comments
    attributes:
      label: Questions or Comments
      description: Please specify the GREI event or resource.
      render: bash
    validations:
      required: false

  - type: textarea
    id: suggestions
    attributes:
      label: Suggestions
      description: Please share any suggestions for improvement.
      render: bash
    validations:
      required: false




















