title: Add title
body:
   - type: checkboxes
      attributes:
      label: If applicable, select the GREI Year 3 Objective, Task, or Deliverable.
      options:
        - label: Community Engagement (All units)
          required: false
        - label: Desirable  Repository Characteristics
          required: false
        - label: Consistent Metadata
          required: false
        - label: Search & Browse
          required: false
        - label: Analytics & Reporting
          required: false
        - label: Use Cases
          required: false
        - label: Connecting Digital Objects
          required: false
        - label: QA/QC
          required: false
        - label: Training & Community Engagement
          required: false

  - type: textarea
    id: idea
    attributes:
      label: Please share your idea or use case. 
      description: 
      render: bash
    validations:
      required: false
  
 
















